export default [{
	"navname":"科室血糖管理",
	"nav_menu":[
		{"name":"患者血糖"},
		{"name":"科室血糖"},
		{"name":"查房单"},
		{"name":"血糖数据导出"}
		]
	},
	{"navname":"临床信息管理",
	"nav_menu":[
		{"name":"床位一览表"},
		{"name":"患者信息管理"},
		{"name":"条形码打印"},
		{"name":"血糖记录单"},
		{"name":"血糖数据维护"},
		{"name":"查房单"},
		{"name":"试条用量统计"},
		{"name":"护士工作量统计"}]
	},{
		"navname":"门诊血糖数据记录",
		"nav_menu":[]
	},{
		"navname":"质量管理",
		"nav_menu":[
			{"name":"试剂管理"},
			{"name":"质控数据查询"},
			{"name":"检验比对管理"}
		]
	}];